---
mock_publisher_node:
  ros__parameters:
    # Mock buttons publisher topic
    button_topic: /interface_buttons
    slip_status_topic: /slip_status
    kidnap_status_topic: /kidnap_status
    battery_state_topic: /battery_state
    stop_status_topic: /stop_status
    buttons_publish_rate: 1.0
    slip_status_publish_rate: 62.0
    kidnap_status_publish_rate: 1.0
    battery_state_publish_rate: 1.0
    stop_status_publish_rate: 62.0
    hazard_topic: /hazard_detection
    wheel_vels_topic: /odom
    lightring_topic: /cmd_lightring

